modules:
  - name: "application"
  - name: "report"

wrap: true

paths:
  jquery: "jquery/dist/jquery.min"
  underscore: "underscore/underscore"
  _string: "underscore.string/dist/underscore.string.min"
  amplify: "amplify/lib/amplify"
  backbone: "backbone/backbone"
  Class: "Class.js/Class"
  select2: "select2/select2"
  handlebarsLib: "handlebars/handlebars"
  handlebars: "lib/handlebars"
  highcharts: "highcharts-release/highcharts"
  spin: "spinjs/spin"
  moment: "moment/moment"
  momentRange: "moment-range/lib/moment-range"
  markerCluster: "leaflet.markercluster/dist/leaflet.markercluster"
  text: "requirejs-text/text"
  quicksilver: "liveupdate/quicksilver"
  liveupdate: "liveupdate/jquery.liveupdate"
  jqueryui: "jquery-ui/js/jquery-ui-1.10.4.custom"
  chachiSlider: "chachi-slider/jquery.chachi-slider"


shim:
  jquery:
    exports: "$"

  underscore:
    exports: "_"

  moment:
    exports: "moment"

  momentRange:
    deps:
      - "moment"
    exports: "momentRange"


  _string:
    exports: "_string"
    deps:
      - "underscore"

  backbone:
    deps:
      - "jquery"
      - "underscore"
    exports: "Backbone"

  liveupdate:
    deps:
      - "jquery"
      - "quicksilver"
    exports: "$"

  jqueryui:
    deps:
      - "jquery"
    exports: "$"

  select2:
    deps:
      - "jquery"
    exports: "$"

  chachiSlider:
    deps:
      - "jquery"
    exports: "$"

  Class:
    exports: "Class"

  amplify:
    exports: "amplify"

  handlebarsLib:
    exports: "Handlebars"

  handlebars:
    exports: "Handlebars"

  highcharts:
    deps:
      - "jquery"
    exports: "Highcharts"

  jquery_ujs:
    deps:
      - "jquery"
    exports: "$"

  bootstrap-sprockets:
    deps:
      - "jquery"

  jquery.remotipart:
    deps:
      - "jquery"
    exports: "$"



